var oldItems = [
    {
      "Title": "Linux image: Request on IT shop and installation on own laptop ",
      "Type": "request",
      "Category": "Unclassified",
      "Description": "How to request and install a Linux image on IT shop as an option to avoid MS Windows on Nokia laptops",
      "Date": "2018-02-02T20:16:45.138Z",
      "Ratings": 0,
      "ID": 205,
      "User": 17,
    },
    {
      "Title": "Customized queries on CEM 17",
      "Type": "share",
      "Category": "Big Data",
      "Description": "Customized queries for CEM 17: Queries over big data",
      "Date": "2018-02-02T20:13:04.471Z",
      "Ratings": 0,
      "ID": 204,
      "User": 17,
      "Duration": 45
    },
    {
      "Title": "Project Management Mentoring for faster Project delivery",
      "Type": "request",
      "Category": "Agility",
      "Description": "Project Management Mentoring for faster Project delivery, what are the tools and techniques which support PMs to deliver stakeholder value?",
      "Date": "2018-01-18T15:03:01.577Z",
      "Ratings": 0,
      "ID": 203,
      "User": 18
    },
    {
      "Title": "Agility",
      "Type": "request",
      "Category": "Agility",
      "Description": "\nNeed to learn about agility",
      "Date": "2018-01-03T14:29:36.198Z",
      "Ratings": 0,
      "ID": 202,
      "User": 19
    },
    {
      "Title": "WONDERBOARD Creation & Customization",
      "Type": "request",
      "Category": "Unclassified",
      "Description": "How to create and customize a Wonderboard for a special event",
      "Date": "2017-11-29T11:07:27.797Z",
      "Ratings": 0,
      "ID": 201,
      "User": 22
    },
    {
      "Title": "hiding small teams in PBI visuals",
      "Type": "request",
      "Category": "Power BI",
      "Description": "due to data privacy reasons I need to hide small teams in showing up in the visuals. The visuals are build on a hierarchy and you can drill into the same. As soon as I put a filter also the accumulated figures of higher level (even not showing on the selected visible) will not be included and thus showing incorrect data. Is there a way to find a workaround?",
      "Date": "2017-11-23T13:23:42.885Z",
      "Ratings": 0,
      "ID": 200,
      "User": 20
    },
    {
      "Title": "Connecting OneDrive data files to PBI for auto-refresh",
      "Type": "share",
      "Category": "Power BI",
      "Description": "I posted in Yammer that I managed to connect OneDrive file with PBI and got auto-refresh working - in case of need feel free to connect me, or have a look into the video (https://nokia.sharepoint.com/portals/hub/_layouts/15/PointPublishing.aspx?app=video&p=p&chid=6cb8cc70-6f9a-4828-9017-4ac9886e7a8f&vid=982e1e5d-a300-4018-90d7-bd3db0f19bbf&from=2)",
      "Date": "2017-11-23T13:19:27.808Z",
      "Ratings": 0,
      "ID": 199,
      "User": 20,
      "Duration": 30
    },
    {
      "Title": "Nokia Custom Theme for Power Bi Desktop",
      "Type": "share",
      "Category": "Power BI",
      "Description": "I have shared a Nokia Theme, including \"Nokia colors\" as well as setting the default font to Arial (Nokia Pure fonts seems not to be supported). In addition I adapted some defaults for the \"Card\" visual. In case of interest you can have a look to the Yammer post (https://www.yammer.com/nokia.com/#/threads/inGroup?type=in_group&feedId=12091838&view=all) or reach out to me. ",
      "Date": "2017-11-23T13:14:52.764Z",
      "Ratings": 0,
      "ID": 198,
      "User": 20,
      "Duration": 15
    },
    {
      "Title": "Active antennas",
      "Type": "request",
      "Category": "Collaboration",
      "Description": "Need a overview of the Active antenna and more numbers in the efficiency than passive antenna systems",
      "Date": "2017-11-01T07:47:00.209Z",
      "Ratings": 0,
      "ID": 195,
      "User": 21
    },
    {
      "Title": "LTE",
      "Type": "request",
      "Category": "Unclassified",
      "Description": "LTE",
      "Date": "2017-10-27T04:55:42.807Z",
      "Ratings": 0,
      "ID": 194,
      "User": 23
    },
    {
      "Title": "VoLTE",
      "Type": "request",
      "Category": "Unclassified",
      "Description": "VoLTE",
      "Date": "2017-10-27T04:55:25.080Z",
      "Ratings": 0,
      "ID": 193,
      "User": 23
    },
    {
      "Title": "SRAN",
      "Type": "request",
      "Category": "Unclassified",
      "Description": "SRAN",
      "Date": "2017-10-27T04:55:08.240Z",
      "Ratings": 0,
      "ID": 192,
      "User": 23
    },
    {
      "Title": "New PC - reinstall OneDrive (OneDrive-Nokia is ok)",
      "Type": "request",
      "Category": "OneDrive",
      "Description": "Am installing my new laptop. \n\nOneDrive - Nokia is synching in the meantime, but the OneDrive folder which I was using to store non-business related documents isn't there. \n\nHow do I set that up again so I can synch those docs as well?\n",
      "Date": "2017-10-16T08:39:07.609Z",
      "Ratings": 0,
      "ID": 191,
      "User": 24
    },
    {
      "Title": "Macros in Emacs",
      "Type": "share",
      "Category": "Get 1 Hour Back",
      "Description": "I can share how to use macros in Emacs to manage text files effectively",
      "Date": "2017-10-12T15:02:47.077Z",
      "Ratings": 0,
      "ID": 190,
      "User": 25,
      "Duration": 15
    },
    {
      "Title": "Time management",
      "Type": "share",
      "Category": "Get 1 Hour Back",
      "Description": "Tips and tricks on time management",
      "Date": "2017-10-03T20:29:05.879Z",
      "Ratings": 0,
      "ID": 189,
      "User": 26,
      "Duration": 15
    },
    {
      "Title": "OneDrive sync",
      "Type": "request",
      "Category": "OneDrive",
      "Description": "I'd like to understand how onedrive sync works from someone who has experience here.",
      "Date": "2017-10-02T08:40:27.284Z",
      "Ratings": 0,
      "ID": 188,
      "User": 27
    },
    {
      "Title": "Improve Sharepoint OnlineTeam site",
      "Type": "request",
      "Category": "SharePoint Online",
      "Description": "Need to improve our team site including site restructuring and need to know how I can do that , what is needed and so forth. ",
      "Date": "2017-09-22T15:13:36.662Z",
      "Ratings": 0,
      "ID": 187,
      "User": 28
    },
    {
      "Title": "Feedback giving and receiving",
      "Type": "share",
      "Category": "Unclassified",
      "Description": "How to Givenchy and receiving valuable feedback. ",
      "Date": "2017-08-30T14:57:37.116Z",
      "Ratings": 0,
      "ID": 186,
      "User": 26,
      "Duration": 45
    },
    {
      "Title": "Sahrepoint online training",
      "Type": "request",
      "Category": "SharePoint Online",
      "Description": "I have watched the basic videos on SPOL but would really like to become more proficient - I normally find my way around things pretty quickly and I have for basic actions - but would like to dig deeper and be able to make the sites look better - has anyone completed any more detailed courses or read any good books / material?",
      "Date": "2017-08-15T09:58:38.657Z",
      "Ratings": 0,
      "ID": 185,
      "User": 29
    },
    {
      "Title": "Improving PowerPoint presentations",
      "Type": "share",
      "Category": "Word, Excel, etc.",
      "Description": "Help you understand what is required for an effective presentation",
      "Date": "2017-07-31T15:44:50.836Z",
      "Ratings": 0,
      "ID": 184,
      "User": 30,
      "Duration": 45
    },
    {
      "Title": "SPOL how can I set the different autorisation level, and how to see the relevance between a document file and a subsite ",
      "Type": "request",
      "Category": "SharePoint Online",
      "Description": "I'm creating a SPOL for a financial project. The goal is:\nallow a team to see in the home page all the things currently ongoing or past and allow some people of the team to contribute for some files and at the same time don't allow us to open others files in other document box.\nMany questions are running in my mind but not resolved because of lack of experience. Thank you ",
      "Date": "2017-07-21T10:27:17.649Z",
      "Ratings": 0,
      "ID": 183,
      "User": 31
    },
    {
      "Title": "Cloud RAN training",
      "Type": "request",
      "Category": "Cloud",
      "Description": "Any Classroom training planned on Cloud RAN",
      "Date": "2017-07-19T10:27:42.989Z",
      "Ratings": 0,
      "ID": 182,
      "User": 32
    },
    {
      "Title": "GIM tool reporting and exporting",
      "Type": "request",
      "Category": "Unclassified",
      "Description": "Hello, I would need some mentoring / tips on certain functionalities in the GIM tool.",
      "Date": "2017-07-11T16:19:51.357Z",
      "Ratings": 0,
      "ID": 181,
      "User": 33
    },
    {
      "Title": "satellite communication and its coordination with terrestrial Network ",
      "Type": "request",
      "Category": "Unclassified",
      "Description": "Dear all,\n\nCould you please help me in identifying the material about the satellite communication and its overlapping & coordination with terrestrial network.\n\nBest Regards\nHarsh",
      "Date": "2017-06-29T13:00:24.239Z",
      "Ratings": 0,
      "ID": 180,
      "User": 34
    },
    {
      "Title": "From ShareNet to SharePoint",
      "Type": "request",
      "Category": "SharePoint Online",
      "Description": "Out team is migrating their needed documents from ShareNet to SharePoint Online. We have figured out how to easiest download documents but would need some suggestion as to where and how to archive the rest of the documents that may be useful later on but wouldn't like to keep them locally. \nThanks in advance! \nBori",
      "Date": "2017-06-27T13:54:10.823Z",
      "Ratings": 0,
      "ID": 179,
      "User": 35
    },
    {
      "Title": "Azure Data Warehouse",
      "Type": "request",
      "Category": "Big Data",
      "Description": "How to set up Azure DB with Data Factory. Auto load data from different sources to a Data Warehouse then use it from Access, Excel, PowerBI... ",
      "Date": "2017-06-16T14:08:47.644Z",
      "Ratings": 0,
      "ID": 178,
      "User": 36
    },
    {
      "Title": "Multivariate Statistics",
      "Type": "share",
      "Category": "Big Data",
      "Description": "I'm an statistician with experience on applied statistics in corporate environment. Those methodologies are being used in the so called Big Data.\nLet me know if you need assistance.\n\n",
      "Date": "2017-06-13T12:43:14.545Z",
      "Ratings": 0,
      "ID": 177,
      "User": 38,
      "Duration": 45
    },
    {
      "Title": "DigiMentor - Getting started",
      "Type": "share",
      "Category": "Unclassified",
      "Description": "Find out what DigiMentor is and how to get started with it.",
      "Date": "2017-06-13T12:26:41.140Z",
      "Ratings": 0,
      "ID": 176,
      "User": 24,
      "Duration": 15
    },
    {
      "Title": "NCIR16A AiO deployment",
      "Type": "share",
      "Category": "Cloud",
      "Description": "I have played around quite a bit with NCIR AiO(All-in-One) deployments as part of my project feel free to contact me.\n- Deployment of VM's \n- Cinder Storage\n- Basic networking etc.,",
      "Date": "2017-06-12T06:46:41.406Z",
      "Ratings": 0,
      "ID": 175,
      "User": 37,
      "Duration": 15
    },
    {
      "Title": "I need help to create an advanced excel macro",
      "Type": "request",
      "Category": "Word, Excel, etc.",
      "Description": "I need help to create an excel macro to send out emails to various recipients with excel attachments.",
      "Date": "2017-06-02T20:35:32.350Z",
      "Ratings": 0,
      "ID": 174,
      "User": 39
    },
    {
      "Title": "Outlook Mailbox Management",
      "Type": "request",
      "Category": "Office 365",
      "Description": "How to manage the mailbox now that we have migrated ? The mailbox is 50GB, which rule to follow for archiving? Local archive or archive in the cloud?",
      "Date": "2017-06-02T09:55:56.844Z",
      "Ratings": 0,
      "ID": 173,
      "User": 40
    },
    {
      "Title": "SharePoint Online - what to do after the very first steps",
      "Type": "request",
      "Category": "SharePoint Online",
      "Description": "I created a SharePoint Online website, but would like to turn it into something that serves my purposes. How/where do I start?\nCan someone help me understand the principles (purpose) of this basic/standard site and help me get started?",
      "Date": "2017-05-11T12:52:41.124Z",
      "Ratings": 0,
      "ID": 172,
      "User": 24
    },
    {
      "Title": "Time management in Espoo campus",
      "Type": "share",
      "Category": "Get 1 Hour Back",
      "Description": "If you are interested on improving your time management with really light \"Getting things done\" mechanism you can start with your Outlook. We can meet for a short 15-45 minute session depending on your need",
      "Date": "2017-04-28T06:24:18.088Z",
      "Ratings": 0,
      "ID": 171,
      "User": 42,
      "Duration": 15
    },
    {
      "Title": "Location Plan",
      "Type": "request",
      "Category": "Collaboration",
      "Description": "I am looking for Location Plan owner and expert in MN",
      "Date": "2017-04-06T08:56:36.620Z",
      "Ratings": 0,
      "ID": 142,
      "User": 41
    },
    {
      "Title": "mobile apps",
      "Type": "share",
      "Category": "O365 on Mobile Devices",
      "Description": "Availability of mobile apps",
      "Date": "2017-03-31T12:56:49.411Z",
      "Ratings": 0,
      "ID": 143,
      "User": 45,
      "Duration": 15
    },
    {
      "Title": "MetaData usage in Sharepoint Online",
      "Type": "request",
      "Category": "SharePoint Online",
      "Description": "Hi,\n\nI would like to understand how to use Metadata in Sharepoint Online.\nMy goal is to create a new field in a libary i created.\nAnd when i upload a document in this library i would like to force the user to define a value for this field.\nThank you",
      "Date": "2017-03-28T16:50:33.944Z",
      "Ratings": 0,
      "ID": 145,
      "User": 44
    },
    {
      "Title": "Setting up Microsoft Authenticator on mobile devices.",
      "Type": "request",
      "Category": "Unclassified",
      "Description": "I'd like to find out how to set up MS Authenticator so as to make it easier for me to connect to e.g. my Office 365 environment from anywhere.",
      "Date": "2017-03-24T15:12:32.069Z",
      "Ratings": 0,
      "ID": 146,
      "User": 24
    },
    {
      "Title": "OneNote Collaboration",
      "Type": "request",
      "Category": "Unclassified",
      "Description": "Requesting support on how to use OneNote for collaboration with my team.  Agenda for staff meetings; action items; etc.  \nI am already familiar with OneNote for more than 15 years but need to get up to speed on the new functionality.",
      "Date": "2017-03-23T20:24:28.890Z",
      "Ratings": 0,
      "ID": 147,
      "User": 43
    },
    {
      "Title": "O365 password for mobile devices",
      "Type": "share",
      "Category": "O365 on Mobile Devices",
      "Description": "quick link to get a password for setting up O365 on your mobile device:\nhttps://account.activedirectory.windowsazure.com/AppPasswords.aspx\n",
      "Date": "2017-03-22T08:18:29.381Z",
      "Ratings": 0,
      "ID": 149,
      "User": 45,
      "Duration": 45
    },
    {
      "Title": "SPOL tips",
      "Type": "request",
      "Category": "SharePoint Online",
      "Description": "Would like to learn how to use task lists and document mng in spol.",
      "Date": "2017-03-21T17:01:02.120Z",
      "Ratings": 0,
      "ID": 148,
      "User": 27
    },
    {
      "Title": "SPOL tips",
      "Type": "share",
      "Category": "SharePoint Online",
      "Description": "Sharing some tips I came accross in my experience with SPOL.",
      "Date": "2017-03-21T16:59:02.950Z",
      "Ratings": 0,
      "ID": 152,
      "User": 27,
      "Duration": 15
    },
    {
      "Title": "JIRA agile project tips and tricks",
      "Type": "request",
      "Category": "Agility",
      "Description": "Would like to get some tips and tricks from JIRA users using it for Agile project mgmt",
      "Date": "2017-03-16T09:20:48.339Z",
      "Ratings": 0,
      "ID": 150,
      "User": 46
    },
    {
      "Title": "Big Data as a Service Intro",
      "Type": "share",
      "Category": "Big Data",
      "Description": "We offer Big Data as a Service in R&D IT.  Please contact me for a brief intro if interested.",
      "Date": "2017-03-16T09:18:54.404Z",
      "Ratings": 0,
      "ID": 151,
      "User": 46,
      "Duration": 15
    },
    {
      "Title": "Healthier Together",
      "Type": "share",
      "Category": "Collaboration",
      "Description": "Did you know there is a new program at Nokia for health and wellbeing in partnership with our digital health vision? Come learn more!",
      "Date": "2017-03-16T08:37:29.864Z",
      "Ratings": 0,
      "ID": 154,
      "User": 47,
      "Duration": 15
    },
    {
      "Title": "Life Saving Rules at Nokia",
      "Type": "share",
      "Category": "Unclassified",
      "Description": "Want to learn more about the 6 principles that rule healthy behaviours? Let me know!",
      "Date": "2017-03-16T08:35:55.778Z",
      "Ratings": 0,
      "ID": 153,
      "User": 47,
      "Duration": 15
    },
    {
      "Title": "Management systems",
      "Type": "share",
      "Category": "Unclassified",
      "Description": "For colleagues that want to learn more about management systems such as quality, health and safety, information security and environment!",
      "Date": "2017-03-16T08:34:33.297Z",
      "Ratings": 0,
      "ID": 157,
      "User": 47,
      "Duration": 15
    },
    {
      "Title": "Reverse Mentoring: Digi topic in exchange for leadership/career dev",
      "Type": "share",
      "Category": "Unclassified",
      "Description": "Looking to improve digi skills, in exchange for leadership/career coaching.",
      "Date": "2017-03-15T15:10:52.988Z",
      "Ratings": 0,
      "ID": 155,
      "User": 48,
      "Duration": 45
    },
    {
      "Title": "Introduction to Microsoft Teams",
      "Type": "share",
      "Category": "Collaboration",
      "Description": "Microsoft Teams is the Microsoft version of Slack. It's made for team to work together on projects. It's available on all devices. \n\nIn 15 minutes I can show you how to install and use the application.\n\nBest for a small team to it together. ",
      "Date": "2017-03-15T08:36:54.719Z",
      "Ratings": 0,
      "ID": 156,
      "User": 49,
      "Duration": 15
    },
    {
      "Title": "Hands-on demonstration of using O365 to co-edit documents",
      "Type": "share",
      "Category": "Word, Excel, etc.",
      "Description": "I can show you how a small group of people can edit together the same document (Excel, PowerPoint, etc.) in a very simple way without the complexity of multiple copies circulating through mails and without having to consolidate the copies.\n\nBest to do with a team (3 to 10 people or more).",
      "Date": "2017-03-15T08:31:57.387Z",
      "Ratings": 0,
      "ID": 160,
      "User": 49,
      "Duration": 30
    },
    {
      "Title": "Outlook Group - set up",
      "Type": "share",
      "Category": "Collaboration",
      "Description": "I can help you learn about setting up a project group in your Outlook (Exchange Online) for efficient collaboration within a (project) team.\nThe group results in a team or project email address, a OneNote notebook and a OneDrive on SharePoint Online.",
      "Date": "2017-03-14T11:46:03.612Z",
      "Ratings": 0,
      "ID": 158,
      "User": 24,
      "Duration": 30
    },
    {
      "Title": "Javascript library for Sharepoint Online",
      "Type": "share",
      "Category": "Office 365",
      "Description": "An easy way to create, read, update and delete data using the SharePoint 2013/Online REST API.",
      "Date": "2017-02-18T15:27:03.021Z",
      "Ratings": 0,
      "ID": 159,
      "User": 50,
      "Duration": 15
    }
  ];
export default oldItems;